@startuml

start
:Start Programm;
fork 
    :bestimmte Wortgruppe wird gesagt;
fork again
    :Knopf am Kopf wird gedrückt;
end merge  
:NAO stellt sich vor;
:NAO fordert Person auf sich vor dem\n Gesicht des NAO zu positionieren;
->5s pause;
:Sofortaufnahme Person wird gespeichert;
:gespeichertes Bild wird mit Datenbank abgeglichen;
if(Wurde eine Übereinstimmung gefunden?) then(yes)
else(no)
    :NAO fragt Person nach Namen;
    :Person antwortet/
    :NAO speichert Name als String;
endif 
:NAO spricht Person mit Namen an;
end

@enduml